language: python
python:
- '3.8'

install:
- pip install -r requirements.txt

services:
  - postgresql

development:
  adapter: postgresql
  encoding: utf8
  database: db_donghee
  username: donghee
  password: 1234

script:
- cd donghee_blog
- ./manage.py migrate
- ./manage.py migrate Post Comment
- python -m pytest

before_install:
- openssl aes-256-cbc -K $encrypted_c050433c86ed_key -iv $encrypted_c050433c86ed_iv
  -in server_info.json.enc -out server_info.json -d

before_script:
- psql -c 'create database db_donghee;' -U postgres