language: python
python:
- '3.8'
install:
- pip install -r requirements.txt
script:
- python donghee_blog/manage.py test
before_install:
- openssl aes-256-cbc -K $encrypted_d0ffdc5fec1f_key -iv $encrypted_d0ffdc5fec1f_iv
  -in /donghee_blog/config/secrets.tar.enc -out /donghee_blog/config/secrets.tar -d
- tar xvf secrets.tar