language: python
python:
- '3.8'
install:
- pip install -r requirements.txt
script:
- cd donghee_blog
- ./manage migrate
- python -m pytest
before_install:
- openssl aes-256-cbc -K $encrypted_c050433c86ed_key -iv $encrypted_c050433c86ed_iv
  -in server_info.json.enc -out server_info.json -d